### ISSUE TITLE
[URGENT] [BUG] Vattic, yo you there?

### ISSUE THREAD

**Issue by cituation** [Vattic/vattic.github.io#1]
It's been four years, what's up man
Faithful is a shit show. You made a bad choice letting xMrVizzy continue on the pack.
Anyways, we're starting a new project called Compliance. If at all you see this, check it out
https://compliancepack.net/ :)

**Comment by TheRandomGamrTRG** [comment]
Hey, Vattic!
Hope you see this. We've been trying to find you for quite some time now.
Hope youre doing better (last we heard of you was Vizzy saying you went homeless)

**Comment by FHLX-J** [comment]
Hello Vattic.  So yes, as you can probably tell from the people above me, we have indeed attempted to regain contact with you for a while. It'd be great to see you back again, Faithful has changed a lot since your disappearance and we have started a new project similar to Faithful due to disagreements we've had with xMrVizzy, who you've given the rights to Faithful. It's called Compliance. If you are willing to make a return and come into contact with us it will be greatly appreciated. Just comment down here with any form of communication you can think of, preferrably discord but it can be any you please. It'd be great if you could make a response.

**Comment by Vattic** [comment]
Hello, I never gave anyone permission to keep the pack going. My disappearance is complicated and I'll not go into it here.

**Comment by Vattic** [comment]
I am open to talk about what is going on. Might be best to move things onto a private channel.

**Comment by FHLX-J** [comment]
> I am open to talk about what is going on. Might be best to move things onto a private channel.

I'm absolutely interested in this, my man. Contact me where you desire. We'll talk. Cheers. We've really missed you, we seriously mean that.

**Comment by verisimal** [comment]
hey can i join in too

**Comment by cituation** [comment]
Vattic, you can contact me on twitter @iscituation or if you have discord, verisimal#3136

It would be appreciated for info on how we can contact you privately :)

But just to be safe, my Skype name is wonsdu

**Comment by FHLX-J** [comment]
In MY Case, You can contact me at ESV#1972 OR ESeriesVIRUS#0873. IF you want to chat to me on Twitter, my twitter is eseriesnub. Thank you for talking to us, and it's good to be in contact with you again. See you soon, cheers and best of luck to you and your struggles.



P.S. If you haven't given anyone permission to continue your work, then OH BOY there's some info you gotta know that's probably gonna piss you off.

**Comment by fabrifachero0003** [comment]
oh my _**G O D**_

**Comment by DiamondCrafter78** [comment]
> Hello, I never gave anyone permission to keep the pack going. My disappearance is complicated and I'll not go into it here.

Wait, so does that mean that the conversation you and Vizzy has was fake/faked? You never gave anyone permission at all?

**Comment by DiamondCrafter78** [comment]
![image](https://user-images.githubusercontent.com/62063949/102686031-cfa44200-421f-11eb-9ee9-cefc645b8bde.png)

**Comment by DiamondCrafter78** [comment]
https://discord.gg/sN9YRQbBv7

**Comment by DiamondCrafter78** [comment]
Oh and just so you know, even if you never gave anyone permission to faithful, Vizzy monetized your pack, when back then, it was free to use and download. Afaik, he's making $100k from this, probably more since more people in this day are playing Minecraft Bedrock (where microtransactions were introduced) than Minecraft Java.

**Comment by DiamondCrafter78** [comment]
Vizzy also claimed that he has "licensed" the pack under his name so that he can sue anyone who try to create a pack similar to Faithful's style.

**Comment by FHLX-J** [comment]
OK So people are now starting to discover that we have regained contact. For anyone new that is seeing this refrain from posting any comments whatsoever and let our team (FHLX, Karthy, Verisimal and TRG) do the work. To Vattic, we should move into a private setting soon to continue talking about this matter. @Vattic

**Comment by DiamondCrafter78** [comment]
> OK So people are now starting to discover that we have regained contact. For anyone new that is seeing this refrain from posting any comments whatsoever and let our team (FHLX, Karthy, Verisimal and TRG) do the work. To Vattic, we should move into a private setting soon to continue talking about this matter.

Invite us to the private channel, please

**Comment by FHLX-J** [comment]
> > OK So people are now starting to discover that we have regained contact. For anyone new that is seeing this refrain from posting any comments whatsoever and let our team (FHLX, Karthy, Verisimal and TRG) do the work. To Vattic, we should move into a private setting soon to continue talking about this matter.
> 
> Invite us to the private channel, please

That's up to Vattic whether he wants to do this.

**Comment by FHLX-J** [comment]
@Vattic In case you want to speak to use and give us your information privately you can join my private repository, I sent an invite you can use to join my private repository. We can open an issue from there and talk in GitHub, or use another form of communication, our preference is Discord (You can find me at ESV#1972).

**Comment by cituation** [comment]
Closed. We found Vattic :)
